// Package sentinel shells out to HashiCorp Sentinel against
// <projectDir>/policies/sentinel/*.sentinel.
//
// Sentinel's CLI is less script-friendly than OPA/Conftest — each policy
// expects a test harness under sentinel-tests/<policy>/ with mock data. This
// adapter takes a pragmatic middle path: it walks the .sentinel files, pairs
// each with a per-policy mock that injects the current Terraform plan JSON
// as tfplan/v2 input, and parses Sentinel's pass/fail output.
//
// When sentinel is not on PATH, the adapter returns Available()=false and a
// single informative Error, so the multi-engine run isn't broken by a missing
// binary.
package sentinel

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/iac-studio/iac-studio/internal/policy/engines"
)

// Binary is the name (or full path) of the sentinel CLI. Overridable for tests.
var Binary = "sentinel"

// PoliciesDir mirrors the layered-terraform blueprint's sentinel layout.
const PoliciesDir = "policies/sentinel"

type sentinelEngine struct{}

// New returns the Sentinel PolicyEngine.
func New() engines.PolicyEngine { return &sentinelEngine{} }

func (s *sentinelEngine) Name() string { return "sentinel" }

func (s *sentinelEngine) Available() bool {
	_, err := exec.LookPath(Binary)
	return err == nil
}

func (s *sentinelEngine) Evaluate(ctx context.Context, in engines.EvalInput) (engines.Result, error) {
	res := engines.Result{Engine: s.Name()}

	if !s.Available() {
		res.Error = "sentinel CLI not found on PATH — install from https://developer.hashicorp.com/sentinel to enable this engine"
		return res, nil
	}
	res.Available = true

	if in.ProjectDir == "" {
		res.Error = "sentinel engine requires a project directory"
		return res, nil
	}
	files, err := discoverPolicyFiles(in.ProjectDir)
	if err != nil {
		res.Error = err.Error()
		return res, err
	}
	if len(files) == 0 {
		return res, nil
	}
	if len(in.PlanJSON) == 0 {
		res.Error = "sentinel engine requires Terraform plan JSON; run `terraform plan -out=tfplan && terraform show -json tfplan` first"
		return res, nil
	}

	// Materialise a temporary harness: a working directory containing the
	// policy, a sentinel.json that declares it, and a mock-tfplan.sentinel
	// carrying the current plan data. We clean up the whole tree on return.
	harness, err := stageHarness(in.PlanJSON)
	if err != nil {
		res.Error = fmt.Sprintf("sentinel harness: %v", err)
		return res, err
	}
	defer func() { _ = os.RemoveAll(harness.dir) }()

	for _, policyPath := range files {
		finding, runErr := runOne(ctx, harness, policyPath)
		if runErr != nil {
			// One bad policy shouldn't blank the rest — record the first
			// error, keep going.
			if res.Error == "" {
				res.Error = fmt.Sprintf("%s: %v", filepath.Base(policyPath), runErr)
			}
			continue
		}
		if finding != nil {
			res.Findings = append(res.Findings, *finding)
		}
	}
	return res, nil
}

func discoverPolicyFiles(projectDir string) ([]string, error) {
	root := filepath.Join(projectDir, PoliciesDir)
	info, err := os.Stat(root)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("%s is not a directory", root)
	}
	matches, err := filepath.Glob(filepath.Join(root, "*.sentinel"))
	if err != nil {
		return nil, err
	}
	sort.Strings(matches)
	return matches, nil
}

// harness carries everything sentinel needs to evaluate one policy at a time:
// a working directory, the mock file that feeds plan data via tfplan/v2, and
// the base config JSON that imports that mock.
type harness struct {
	dir      string
	mockPath string
}

// stageHarness builds a tempdir containing:
//   - tfplan.json (the raw plan)
//   - mock-tfplan.sentinel (maps tfplan/v2 → the plan JSON)
//   - sentinel.json (config that injects the mock for every run)
//
// Sentinel's Go-based CLI discovers mocks from sentinel.json under the cwd.
func stageHarness(planJSON []byte) (*harness, error) {
	dir, err := os.MkdirTemp("", "iac-sentinel-*")
	if err != nil {
		return nil, err
	}
	planFile := filepath.Join(dir, "tfplan.json")
	if err := os.WriteFile(planFile, planJSON, 0o600); err != nil {
		return nil, err
	}
	mockFile := filepath.Join(dir, "mock-tfplan.sentinel")
	mockBody := `# Auto-generated by IaC Studio.
import "json"
import "file"

plan = json.unmarshal(file.read("tfplan.json"))

# Tfplan/v2 surface — the minimum subset real policies use.
resource_changes = plan.resource_changes else []
planned_values  = plan.planned_values  else {}
variables       = plan.variables       else {}
`
	if err := os.WriteFile(mockFile, []byte(mockBody), 0o600); err != nil {
		return nil, err
	}
	cfg := map[string]any{
		"mock": map[string]any{
			"tfplan/v2": "mock-tfplan.sentinel",
		},
	}
	cfgBytes, _ := json.Marshal(cfg)
	if err := os.WriteFile(filepath.Join(dir, "sentinel.json"), cfgBytes, 0o600); err != nil {
		return nil, err
	}
	return &harness{dir: dir, mockPath: mockFile}, nil
}

// runOne executes `sentinel apply <policy>` against the harness and converts
// a failing result into an engines.Finding. A passing result returns (nil, nil).
func runOne(ctx context.Context, h *harness, policyPath string) (*engines.Finding, error) {
	// sentinel resolves imports relative to its working directory; we use the
	// absolute policy path so the user's files aren't moved or copied.
	absPolicy, err := filepath.Abs(policyPath)
	if err != nil {
		return nil, err
	}
	cmd := exec.CommandContext(ctx, Binary, "apply", "-trace", absPolicy)
	cmd.Dir = h.dir
	out, err := cmd.CombinedOutput()
	output := string(out)
	if err == nil {
		// Exit 0 means the policy's main rule passed; nothing to report.
		return nil, nil
	}
	if _, ok := err.(*exec.ExitError); !ok {
		// Non-exit error (binary missing mid-run, context cancelled, …).
		return nil, err
	}
	// Sentinel prints something like "Result: false" when the policy fails.
	// We surface the combined output as the finding message so users get the
	// full -trace context.
	msg := strings.TrimSpace(output)
	if msg == "" {
		msg = "sentinel policy failed"
	}
	base := filepath.Base(policyPath)
	policyID := strings.TrimSuffix(base, ".sentinel")
	return &engines.Finding{
		Engine:     "sentinel",
		PolicyID:   policyID,
		PolicyName: policyID,
		Severity:   engines.SeverityError,
		Category:   "compliance",
		Message:    msg,
		PolicyFile: policyPath,
	}, nil
}
