package pipeline

import (
	"fmt"
	"regexp"
	"strings"
)

// Generator creates CI/CD pipeline configs from IaC project settings.
// Instead of writing YAML by hand, DevOps engineers configure their pipeline
// through the UI and get a production-ready CI config generated.
type Generator struct{}

// safeYAMLValue checks that a string is safe to embed in generated YAML.
// Rejects characters that could cause YAML injection or shell injection
// in generated `run:` steps.
var safeSlug = regexp.MustCompile(`^[a-zA-Z0-9._/-]+$`)

func validateConfig(c PipelineConfig) error {
	if c.WorkingDir != "" && !safeSlug.MatchString(c.WorkingDir) {
		return fmt.Errorf("unsafe working directory %q: only alphanumeric, dots, slashes, hyphens allowed", c.WorkingDir)
	}
	for _, env := range c.Environments {
		if !safeSlug.MatchString(env) {
			return fmt.Errorf("unsafe environment name %q", env)
		}
	}
	if c.TerraformVersion != "" && !safeSlug.MatchString(c.TerraformVersion) {
		return fmt.Errorf("unsafe terraform version %q", c.TerraformVersion)
	}
	return nil
}

func New() *Generator {
	return &Generator{}
}

// PipelineConfig describes the desired CI/CD behavior.
type PipelineConfig struct {
	Provider       string            `json:"provider"`        // github | gitlab | bitbucket
	Tool           string            `json:"tool"`            // terraform | opentofu | ansible
	Environments   []string          `json:"environments"`    // ["dev", "staging", "prod"]
	TerraformVersion string          `json:"terraform_version"`
	AutoPlan       bool              `json:"auto_plan"`       // run plan on PR
	AutoApplyDev   bool              `json:"auto_apply_dev"`  // auto-apply to dev on merge
	RequireApproval []string         `json:"require_approval"` // envs needing manual approval
	RunPolicy      bool              `json:"run_policy"`      // run policy checks
	RunCostEstimate bool             `json:"run_cost_estimate"` // run cost estimation
	NotifySlack    bool              `json:"notify_slack"`
	StateBackend   string            `json:"state_backend"`   // s3 | gcs | azure | terraform-cloud
	WorkingDir     string            `json:"working_dir"`     // terraform directory within repo
	ExtraSteps     []string          `json:"extra_steps"`     // additional commands to run
}

// GeneratedPipeline is the output.
type GeneratedPipeline struct {
	Provider    string `json:"provider"`
	Filename    string `json:"filename"`    // e.g., ".github/workflows/terraform.yml"
	Content     string `json:"content"`
	Description string `json:"description"`
}

// Generate creates a CI/CD pipeline config file.
func (g *Generator) Generate(config PipelineConfig) (*GeneratedPipeline, error) {
	if err := validateConfig(config); err != nil {
		return nil, err
	}
	switch config.Provider {
	case "github":
		return g.generateGitHub(config)
	case "gitlab":
		return g.generateGitLab(config)
	default:
		return nil, fmt.Errorf("unsupported CI provider: %s (supported: github, gitlab)", config.Provider)
	}
}

func (g *Generator) generateGitHub(c PipelineConfig) (*GeneratedPipeline, error) {
	binary := "terraform"
	if c.Tool == "opentofu" {
		binary = "tofu"
	}

	tfVersion := c.TerraformVersion
	if tfVersion == "" {
		tfVersion = "1.9.0"
	}

	workDir := c.WorkingDir
	if workDir == "" {
		workDir = "."
	}

	var sb strings.Builder

	sb.WriteString(fmt.Sprintf(`# Generated by IaC Studio — %s CI/CD Pipeline
# Tool: %s | Environments: %s

name: Infrastructure

on:
  push:
    branches: [main]
    paths:
      - '%s/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches: [main]
    paths:
      - '%s/**'

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false

`, c.Tool, c.Tool, strings.Join(c.Environments, ", "), workDir, workDir))

	sb.WriteString("jobs:\n")

	// --- Validate job (runs on every PR) ---
	sb.WriteString(fmt.Sprintf(`  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup %s
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '%s'

      - name: Format Check
        working-directory: %s
        run: %s fmt -check -recursive

      - name: Init
        working-directory: %s
        run: %s init -backend=false

      - name: Validate
        working-directory: %s
        run: %s validate
`, c.Tool, tfVersion, workDir, binary, workDir, binary, workDir, binary))

	// --- Plan job (runs on PR) ---
	if c.AutoPlan {
		for _, env := range c.Environments {
			sb.WriteString(fmt.Sprintf(`
  plan-%s:
    name: Plan (%s)
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'pull_request'
    environment: %s
    steps:
      - uses: actions/checkout@v4

      - name: Setup %s
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '%s'

      - name: Init
        working-directory: %s
        run: %s init

      - name: Select Workspace
        working-directory: %s
        run: %s workspace select %s || %s workspace new %s

      - name: Plan
        id: plan
        working-directory: %s
        run: |
          %s plan -var-file=env/%s.tfvars -no-color -out=tfplan 2>&1 | tee plan-output.txt
          echo "plan_exit_code=$?" >> $GITHUB_OUTPUT

      - name: Comment Plan on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('plan-output.txt', 'utf8');
            const body = 'Plan (%s)\n\n<details><summary>Show</summary>\n\n' + output.substring(0, 60000) + '\n\n</details>';
            github.rest.issues.createComment({ issue_number: context.issue.number, owner: context.repo.owner, repo: context.repo.repo, body });
`, env, env, env, c.Tool, tfVersion, workDir, binary, workDir, binary, env, binary, env, workDir, binary, env, env))
		}
	}

	// --- Apply jobs (runs on merge to main) ---
	for i, env := range c.Environments {
		needsApproval := contains(c.RequireApproval, env)
		autoApply := env == "dev" && c.AutoApplyDev

		needs := "validate"
		if i > 0 {
			needs = fmt.Sprintf("apply-%s", c.Environments[i-1])
		}

		sb.WriteString(fmt.Sprintf(`
  apply-%s:
    name: Apply (%s)
    runs-on: ubuntu-latest
    needs: %s
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: %s
`, env, env, needs, env))

		if !autoApply || needsApproval {
			// GitHub environment protection rules handle approval
		}

		sb.WriteString(fmt.Sprintf(`    steps:
      - uses: actions/checkout@v4

      - name: Setup %s
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '%s'

      - name: Init
        working-directory: %s
        run: %s init

      - name: Select Workspace
        working-directory: %s
        run: %s workspace select %s || %s workspace new %s

      - name: Plan
        working-directory: %s
        run: %s plan -var-file=env/%s.tfvars -no-color -out=tfplan

      - name: Apply
        working-directory: %s
        run: %s apply -auto-approve tfplan
`, c.Tool, tfVersion, workDir, binary, workDir, binary, env, binary, env, workDir, binary, env, workDir, binary))

		if c.NotifySlack {
			sb.WriteString(fmt.Sprintf(`
      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "%s deploy to %s: ${{ job.status }}",
              "channel": "#infrastructure"
            }
`, c.Tool, env))
		}
	}

	return &GeneratedPipeline{
		Provider:    "github",
		Filename:    ".github/workflows/terraform.yml",
		Content:     sb.String(),
		Description: fmt.Sprintf("GitHub Actions pipeline for %s with %d environments", c.Tool, len(c.Environments)),
	}, nil
}

func (g *Generator) generateGitLab(c PipelineConfig) (*GeneratedPipeline, error) {
	binary := "terraform"
	if c.Tool == "opentofu" {
		binary = "tofu"
	}

	tfVersion := c.TerraformVersion
	if tfVersion == "" {
		tfVersion = "1.9.0"
	}

	workDir := c.WorkingDir
	if workDir == "" {
		workDir = "."
	}

	var sb strings.Builder

	sb.WriteString(fmt.Sprintf(`# Generated by IaC Studio — %s CI/CD Pipeline
# Tool: %s | Environments: %s

image:
  name: hashicorp/terraform:%s
  entrypoint: [""]

variables:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

stages:
  - validate
  - plan
  - apply

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - %s/.terraform/

validate:
  stage: validate
  script:
    - cd %s
    - %s init -backend=false
    - %s fmt -check -recursive
    - %s validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
`, c.Tool, c.Tool, strings.Join(c.Environments, ", "), tfVersion, workDir, workDir, binary, binary, binary))

	for _, env := range c.Environments {
		needsApproval := contains(c.RequireApproval, env)

		// Plan stage
		sb.WriteString(fmt.Sprintf(`
plan:%s:
  stage: plan
  needs: [validate]
  script:
    - cd %s
    - %s init
    - %s workspace select %s || %s workspace new %s
    - %s plan -var-file=env/%s.tfvars -no-color -out=tfplan
  artifacts:
    paths:
      - %s/tfplan
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
`, env, workDir, binary, binary, env, binary, env, binary, env, workDir))

		// Apply stage
		sb.WriteString(fmt.Sprintf(`
apply:%s:
  stage: apply
  needs: ["plan:%s"]
  environment:
    name: %s
  script:
    - cd %s
    - %s init
    - %s workspace select %s
    - %s apply -auto-approve tfplan
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
`, env, env, env, workDir, binary, binary, env, binary))

		if needsApproval {
			sb.WriteString("  when: manual\n")
			sb.WriteString("  allow_failure: false\n")
		}
	}

	return &GeneratedPipeline{
		Provider:    "gitlab",
		Filename:    ".gitlab-ci.yml",
		Content:     sb.String(),
		Description: fmt.Sprintf("GitLab CI pipeline for %s with %d environments", c.Tool, len(c.Environments)),
	}, nil
}

// DefaultConfig returns a sensible default pipeline configuration.
func DefaultConfig(tool string) PipelineConfig {
	return PipelineConfig{
		Provider:         "github",
		Tool:             tool,
		Environments:     []string{"dev", "staging", "prod"},
		TerraformVersion: "1.9.0",
		AutoPlan:         true,
		AutoApplyDev:     true,
		RequireApproval:  []string{"staging", "prod"},
		RunPolicy:        true,
		RunCostEstimate:  true,
		NotifySlack:      false,
		StateBackend:     "s3",
		WorkingDir:       ".",
	}
}

func contains(slice []string, item string) bool {
	for _, s := range slice {
		if s == item {
			return true
		}
	}
	return false
}
