package catalog

func azureResources() []Resource {
	return []Resource{
		// ─── Networking ───
		{Type: "azurerm_virtual_network", Label: "Virtual Network", Icon: "🌐", Category: "Networking", Provider: "azurerm",
			Defaults: map[string]any{"name": "my-vnet", "location": "eastus", "address_space": "10.0.0.0/16"},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "location", Type: "select", Default: "eastus", Options: []string{"eastus", "eastus2", "westus", "westus2", "centralus", "westeurope", "northeurope", "southeastasia"}},
				{Name: "address_space", Type: "string", Required: true, Default: "10.0.0.0/16"},
			},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_subnet", Label: "Subnet", Icon: "📡", Category: "Networking", Provider: "azurerm",
			Defaults: map[string]any{"name": "my-subnet", "address_prefixes": "10.0.1.0/24"},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "address_prefixes", Type: "string", Required: true, Default: "10.0.1.0/24"},
			},
			ConnectsTo:  []string{"azurerm_virtual_network", "azurerm_resource_group"},
			ConnectsVia: map[string]string{"virtual_network_name": "azurerm_virtual_network", "resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_network_security_group", Label: "Network Security Group", Icon: "🛡️", Category: "Networking", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-nsg", "location": "eastus"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_public_ip", Label: "Public IP", Icon: "📌", Category: "Networking", Provider: "azurerm",
			Defaults: map[string]any{"name": "my-pip", "location": "eastus", "allocation_method": "Static", "sku": "Standard"},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "allocation_method", Type: "select", Default: "Static", Options: []string{"Static", "Dynamic"}},
				{Name: "sku", Type: "select", Default: "Standard", Options: []string{"Basic", "Standard"}},
			},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_nat_gateway", Label: "NAT Gateway", Icon: "🔄", Category: "Networking", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-nat", "location": "eastus", "sku_name": "Standard"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_dns_zone", Label: "DNS Zone", Icon: "🌐", Category: "Networking", Provider: "azurerm",
			Defaults:    map[string]any{"name": "example.com"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_private_dns_zone", Label: "Private DNS Zone", Icon: "🔒", Category: "Networking", Provider: "azurerm",
			Defaults:    map[string]any{"name": "privatelink.database.windows.net"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_application_gateway", Label: "Application Gateway", Icon: "🚪", Category: "Networking", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-appgw", "location": "eastus"},
			ConnectsTo:  []string{"azurerm_resource_group", "azurerm_subnet"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_virtual_network_gateway", Label: "VPN Gateway", Icon: "🔐", Category: "Networking", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-vpn-gw", "location": "eastus", "type": "Vpn", "sku": "VpnGw1"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},

		// ─── Compute ───
		{Type: "azurerm_resource_group", Label: "Resource Group", Icon: "📁", Category: "Core", Provider: "azurerm",
			Defaults: map[string]any{"name": "my-rg", "location": "eastus"},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "location", Type: "select", Required: true, Default: "eastus", Options: []string{"eastus", "eastus2", "westus", "westus2", "centralus", "westeurope", "northeurope", "southeastasia"}},
			},
		},
		{Type: "azurerm_linux_virtual_machine", Label: "Linux VM", Icon: "🖥️", Category: "Compute", Provider: "azurerm",
			Defaults: map[string]any{"name": "my-vm", "location": "eastus", "size": "Standard_B2s", "admin_username": "azureuser"},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "size", Type: "select", Required: true, Default: "Standard_B2s",
					Options: []string{"Standard_B1s", "Standard_B2s", "Standard_B2ms", "Standard_D2s_v5", "Standard_D4s_v5", "Standard_E2s_v5", "Standard_F2s_v2"}},
				{Name: "admin_username", Type: "string", Default: "azureuser"},
			},
			ConnectsTo:  []string{"azurerm_resource_group", "azurerm_network_interface"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_windows_virtual_machine", Label: "Windows VM", Icon: "🪟", Category: "Compute", Provider: "azurerm",
			Defaults: map[string]any{"name": "my-win-vm", "location": "eastus", "size": "Standard_B2s", "admin_username": "azureuser"},
		},
		{Type: "azurerm_virtual_machine_scale_set", Label: "VM Scale Set", Icon: "📊", Category: "Compute", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-vmss", "location": "eastus", "sku": "Standard_B2s", "instances": 2},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_network_interface", Label: "Network Interface", Icon: "🔌", Category: "Compute", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-nic", "location": "eastus"},
			ConnectsTo:  []string{"azurerm_resource_group", "azurerm_subnet"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_kubernetes_cluster", Label: "AKS Cluster", Icon: "☸️", Category: "Compute", Provider: "azurerm",
			Defaults: map[string]any{"name": "my-aks", "location": "eastus", "dns_prefix": "myaks", "default_node_pool_vm_size": "Standard_D2s_v5", "default_node_pool_count": 3},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "location", Type: "select", Default: "eastus", Options: []string{"eastus", "eastus2", "westus2", "westeurope", "southeastasia"}},
				{Name: "dns_prefix", Type: "string", Required: true},
			},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_container_registry", Label: "Container Registry", Icon: "📦", Category: "Compute", Provider: "azurerm",
			Defaults:    map[string]any{"name": "myacr", "location": "eastus", "sku": "Basic", "admin_enabled": false},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_container_group", Label: "Container Instance", Icon: "🐳", Category: "Compute", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-aci", "location": "eastus", "os_type": "Linux"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_function_app", Label: "Function App", Icon: "⚡", Category: "Compute", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-func", "location": "eastus"},
			ConnectsTo:  []string{"azurerm_resource_group", "azurerm_service_plan"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group", "service_plan_id": "azurerm_service_plan"},
		},
		{Type: "azurerm_service_plan", Label: "App Service Plan", Icon: "📋", Category: "Compute", Provider: "azurerm",
			Defaults: map[string]any{"name": "my-plan", "location": "eastus", "os_type": "Linux", "sku_name": "B1"},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "os_type", Type: "select", Default: "Linux", Options: []string{"Linux", "Windows"}},
				{Name: "sku_name", Type: "select", Default: "B1", Options: []string{"F1", "B1", "B2", "B3", "S1", "S2", "P1v2", "P2v2", "P3v2"}},
			},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_linux_web_app", Label: "Web App (Linux)", Icon: "🌐", Category: "Compute", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-webapp", "location": "eastus"},
			ConnectsTo:  []string{"azurerm_resource_group", "azurerm_service_plan"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group", "service_plan_id": "azurerm_service_plan"},
		},

		// ─── Storage ───
		{Type: "azurerm_storage_account", Label: "Storage Account", Icon: "🪣", Category: "Storage", Provider: "azurerm",
			Defaults: map[string]any{"name": "mystorageacct", "location": "eastus", "account_tier": "Standard", "account_replication_type": "LRS"},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true, Description: "3-24 chars, lowercase + numbers only"},
				{Name: "account_tier", Type: "select", Default: "Standard", Options: []string{"Standard", "Premium"}},
				{Name: "account_replication_type", Type: "select", Default: "LRS", Options: []string{"LRS", "GRS", "RAGRS", "ZRS", "GZRS", "RAGZRS"}},
			},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_storage_container", Label: "Blob Container", Icon: "📦", Category: "Storage", Provider: "azurerm",
			Defaults:    map[string]any{"name": "content", "container_access_type": "private"},
			ConnectsTo:  []string{"azurerm_storage_account"},
			ConnectsVia: map[string]string{"storage_account_name": "azurerm_storage_account"},
		},
		{Type: "azurerm_managed_disk", Label: "Managed Disk", Icon: "💾", Category: "Storage", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-disk", "location": "eastus", "storage_account_type": "Premium_LRS", "disk_size_gb": 128, "create_option": "Empty"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},

		// ─── Database ───
		{Type: "azurerm_mssql_server", Label: "SQL Server", Icon: "🗄️", Category: "Database", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-sql-server", "location": "eastus", "version": "12.0", "administrator_login": "sqladmin"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_mssql_database", Label: "SQL Database", Icon: "📊", Category: "Database", Provider: "azurerm",
			Defaults:    map[string]any{"name": "mydb", "sku_name": "S0"},
			ConnectsTo:  []string{"azurerm_mssql_server"},
			ConnectsVia: map[string]string{"server_id": "azurerm_mssql_server"},
		},
		{Type: "azurerm_postgresql_flexible_server", Label: "PostgreSQL Flexible", Icon: "🐘", Category: "Database", Provider: "azurerm",
			Defaults: map[string]any{"name": "my-pg", "location": "eastus", "sku_name": "B_Standard_B1ms", "version": "15", "administrator_login": "pgadmin"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_mysql_flexible_server", Label: "MySQL Flexible", Icon: "🐬", Category: "Database", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-mysql", "location": "eastus", "sku_name": "B_Standard_B1ms", "version": "8.0.21"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_cosmosdb_account", Label: "Cosmos DB", Icon: "🌍", Category: "Database", Provider: "azurerm",
			Defaults: map[string]any{"name": "my-cosmos", "location": "eastus", "offer_type": "Standard", "kind": "GlobalDocumentDB"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_redis_cache", Label: "Azure Cache for Redis", Icon: "⚡", Category: "Database", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-redis", "location": "eastus", "capacity": 1, "family": "C", "sku_name": "Basic"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},

		// ─── Security & Identity ───
		{Type: "azurerm_key_vault", Label: "Key Vault", Icon: "🔐", Category: "Security", Provider: "azurerm",
			Defaults: map[string]any{"name": "my-kv", "location": "eastus", "sku_name": "standard", "purge_protection_enabled": false},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_user_assigned_identity", Label: "Managed Identity", Icon: "🔑", Category: "Security", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-identity", "location": "eastus"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},

		// ─── Load Balancing ───
		{Type: "azurerm_lb", Label: "Load Balancer", Icon: "⚖️", Category: "Load Balancing", Provider: "azurerm",
			Defaults: map[string]any{"name": "my-lb", "location": "eastus", "sku": "Standard"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_frontdoor", Label: "Front Door", Icon: "🚪", Category: "Load Balancing", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-fd"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},

		// ─── Monitoring ───
		{Type: "azurerm_log_analytics_workspace", Label: "Log Analytics", Icon: "📋", Category: "Monitoring", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-law", "location": "eastus", "sku": "PerGB2018", "retention_in_days": 30},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_application_insights", Label: "App Insights", Icon: "🔍", Category: "Monitoring", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-ai", "location": "eastus", "application_type": "web"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_monitor_action_group", Label: "Action Group", Icon: "🚨", Category: "Monitoring", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-ag", "short_name": "myag"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},

		// ─── Messaging ───
		{Type: "azurerm_servicebus_namespace", Label: "Service Bus", Icon: "📬", Category: "Messaging", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-sb", "location": "eastus", "sku": "Standard"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
		{Type: "azurerm_eventhub_namespace", Label: "Event Hub", Icon: "📨", Category: "Messaging", Provider: "azurerm",
			Defaults:    map[string]any{"name": "my-eh", "location": "eastus", "sku": "Standard"},
			ConnectsTo:  []string{"azurerm_resource_group"},
			ConnectsVia: map[string]string{"resource_group_name": "azurerm_resource_group"},
		},
	}
}
