package catalog

// awsExtraResources returns AWS resources beyond the base set in catalog.go.
func awsExtraResources() []Resource {
	return []Resource{
		// ─── Compute (additional) ───
		{Type: "aws_autoscaling_group", Label: "Auto Scaling Group", Icon: "📈", Category: "Compute", Provider: "aws",
			Defaults: map[string]any{"name": "my-asg", "min_size": 1, "max_size": 4, "desired_capacity": 2},
			ConnectsTo:  []string{"aws_launch_template", "aws_subnet"},
			ConnectsVia: map[string]string{"launch_template": "aws_launch_template"},
		},
		{Type: "aws_ecs_service", Label: "ECS Service", Icon: "🚢", Category: "Compute", Provider: "aws",
			Defaults:    map[string]any{"name": "my-service", "desired_count": 2, "launch_type": "FARGATE"},
			ConnectsTo:  []string{"aws_ecs_cluster"},
			ConnectsVia: map[string]string{"cluster": "aws_ecs_cluster"},
		},
		{Type: "aws_ecs_task_definition", Label: "ECS Task", Icon: "📋", Category: "Compute", Provider: "aws",
			Defaults: map[string]any{"family": "my-task", "network_mode": "awsvpc", "requires_compatibilities": "FARGATE", "cpu": "256", "memory": "512"},
		},
		{Type: "aws_eks_cluster", Label: "EKS Cluster", Icon: "☸️", Category: "Compute", Provider: "aws",
			Defaults: map[string]any{"name": "my-eks"},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "version", Type: "select", Default: "1.29", Options: []string{"1.29", "1.28", "1.27"}},
			},
			ConnectsTo:  []string{"aws_iam_role", "aws_subnet"},
			ConnectsVia: map[string]string{"role_arn": "aws_iam_role"},
		},
		{Type: "aws_eks_node_group", Label: "EKS Node Group", Icon: "🏊", Category: "Compute", Provider: "aws",
			Defaults:    map[string]any{"node_group_name": "my-nodes", "instance_types": "t3.medium", "desired_size": 2, "min_size": 1, "max_size": 4},
			ConnectsTo:  []string{"aws_eks_cluster", "aws_subnet"},
			ConnectsVia: map[string]string{"cluster_name": "aws_eks_cluster"},
		},
		{Type: "aws_lightsail_instance", Label: "Lightsail Instance", Icon: "💡", Category: "Compute", Provider: "aws",
			Defaults: map[string]any{"name": "my-lightsail", "availability_zone": "us-east-1a", "blueprint_id": "ubuntu_22_04", "bundle_id": "nano_3_0"},
		},
		{Type: "aws_batch_compute_environment", Label: "Batch Compute", Icon: "⚙️", Category: "Compute", Provider: "aws",
			Defaults: map[string]any{"compute_environment_name": "my-batch", "type": "MANAGED"},
		},

		// ─── Storage (additional) ───
		{Type: "aws_s3_bucket_versioning", Label: "S3 Versioning", Icon: "🔄", Category: "Storage", Provider: "aws",
			Defaults:    map[string]any{"status": "Enabled"},
			ConnectsTo:  []string{"aws_s3_bucket"},
			ConnectsVia: map[string]string{"bucket": "aws_s3_bucket"},
		},
		{Type: "aws_s3_bucket_server_side_encryption_configuration", Label: "S3 Encryption", Icon: "🔐", Category: "Storage", Provider: "aws",
			ConnectsTo:  []string{"aws_s3_bucket"},
			ConnectsVia: map[string]string{"bucket": "aws_s3_bucket"},
		},
		{Type: "aws_s3_bucket_public_access_block", Label: "S3 Public Access Block", Icon: "🚫", Category: "Storage", Provider: "aws",
			Defaults:    map[string]any{"block_public_acls": true, "block_public_policy": true, "ignore_public_acls": true, "restrict_public_buckets": true},
			ConnectsTo:  []string{"aws_s3_bucket"},
			ConnectsVia: map[string]string{"bucket": "aws_s3_bucket"},
		},
		{Type: "aws_ecr_repository", Label: "ECR Repository", Icon: "📦", Category: "Storage", Provider: "aws",
			Defaults: map[string]any{"name": "my-app", "image_tag_mutability": "MUTABLE"},
		},
		{Type: "aws_glacier_vault", Label: "Glacier Vault", Icon: "🧊", Category: "Storage", Provider: "aws",
			Defaults: map[string]any{"name": "my-vault"},
		},

		// ─── Database (additional) ───
		{Type: "aws_db_subnet_group", Label: "DB Subnet Group", Icon: "📡", Category: "Database", Provider: "aws",
			Defaults: map[string]any{"name": "my-db-subnet-group"},
			ConnectsTo:  []string{"aws_subnet"},
			ConnectsVia: map[string]string{"subnet_ids": "aws_subnet"},
		},
		{Type: "aws_rds_cluster", Label: "Aurora Cluster", Icon: "🌌", Category: "Database", Provider: "aws",
			Defaults: map[string]any{"cluster_identifier": "my-aurora", "engine": "aurora-postgresql", "master_username": "admin"},
		},
		{Type: "aws_neptune_cluster", Label: "Neptune (Graph DB)", Icon: "🔗", Category: "Database", Provider: "aws",
			Defaults: map[string]any{"cluster_identifier": "my-neptune", "engine": "neptune"},
		},
		{Type: "aws_docdb_cluster", Label: "DocumentDB", Icon: "📄", Category: "Database", Provider: "aws",
			Defaults: map[string]any{"cluster_identifier": "my-docdb", "engine": "docdb", "master_username": "admin"},
		},
		{Type: "aws_redshift_cluster", Label: "Redshift Cluster", Icon: "📊", Category: "Database", Provider: "aws",
			Defaults: map[string]any{"cluster_identifier": "my-redshift", "node_type": "dc2.large", "cluster_type": "single-node", "master_username": "admin"},
		},
		{Type: "aws_opensearch_domain", Label: "OpenSearch", Icon: "🔍", Category: "Database", Provider: "aws",
			Defaults: map[string]any{"domain_name": "my-search", "engine_version": "OpenSearch_2.11"},
		},

		// ─── Networking (additional) ───
		{Type: "aws_vpc_peering_connection", Label: "VPC Peering", Icon: "🤝", Category: "Networking", Provider: "aws",
			Defaults:    map[string]any{},
			ConnectsTo:  []string{"aws_vpc"},
			ConnectsVia: map[string]string{"vpc_id": "aws_vpc"},
		},
		{Type: "aws_cloudfront_distribution", Label: "CloudFront CDN", Icon: "🌍", Category: "Networking", Provider: "aws",
			Defaults: map[string]any{"enabled": true, "default_root_object": "index.html"},
		},
		{Type: "aws_api_gateway_rest_api", Label: "API Gateway (REST)", Icon: "🚪", Category: "Networking", Provider: "aws",
			Defaults: map[string]any{"name": "my-api"},
		},
		{Type: "aws_apigatewayv2_api", Label: "API Gateway (HTTP)", Icon: "🚀", Category: "Networking", Provider: "aws",
			Defaults: map[string]any{"name": "my-http-api", "protocol_type": "HTTP"},
		},
		{Type: "aws_lb_listener", Label: "LB Listener", Icon: "👂", Category: "Load Balancing", Provider: "aws",
			Defaults:    map[string]any{"port": 80, "protocol": "HTTP", "default_action_type": "forward"},
			ConnectsTo:  []string{"aws_lb", "aws_lb_target_group"},
			ConnectsVia: map[string]string{"load_balancer_arn": "aws_lb"},
		},

		// ─── Security (additional) ───
		{Type: "aws_iam_instance_profile", Label: "Instance Profile", Icon: "👤", Category: "Security", Provider: "aws",
			Defaults:    map[string]any{"name": "my-profile"},
			ConnectsTo:  []string{"aws_iam_role"},
			ConnectsVia: map[string]string{"role": "aws_iam_role"},
		},
		{Type: "aws_iam_policy_attachment", Label: "Policy Attachment", Icon: "📎", Category: "Security", Provider: "aws",
			Defaults:    map[string]any{"name": "my-attachment"},
			ConnectsTo:  []string{"aws_iam_role", "aws_iam_policy"},
			ConnectsVia: map[string]string{"roles": "aws_iam_role", "policy_arn": "aws_iam_policy"},
		},
		{Type: "aws_secretsmanager_secret", Label: "Secrets Manager", Icon: "🤫", Category: "Security", Provider: "aws",
			Defaults: map[string]any{"name": "my-secret"},
		},
		{Type: "aws_ssm_parameter", Label: "SSM Parameter", Icon: "📝", Category: "Security", Provider: "aws",
			Defaults: map[string]any{"name": "/app/config/key", "type": "String", "value": "my-value"},
		},
		{Type: "aws_acm_certificate", Label: "ACM Certificate", Icon: "📜", Category: "Security", Provider: "aws",
			Defaults: map[string]any{"domain_name": "example.com", "validation_method": "DNS"},
		},
		{Type: "aws_wafv2_web_acl", Label: "WAF Web ACL", Icon: "🛡️", Category: "Security", Provider: "aws",
			Defaults: map[string]any{"name": "my-waf", "scope": "REGIONAL"},
		},

		// ─── Monitoring (additional) ───
		{Type: "aws_cloudwatch_metric_alarm", Label: "CloudWatch Alarm", Icon: "🚨", Category: "Monitoring", Provider: "aws",
			Defaults: map[string]any{"alarm_name": "high-cpu", "comparison_operator": "GreaterThanThreshold", "evaluation_periods": 2, "metric_name": "CPUUtilization", "namespace": "AWS/EC2", "period": 300, "statistic": "Average", "threshold": 80},
		},
		{Type: "aws_cloudwatch_dashboard", Label: "CloudWatch Dashboard", Icon: "📊", Category: "Monitoring", Provider: "aws",
			Defaults: map[string]any{"dashboard_name": "my-dashboard"},
		},

		// ─── Messaging (additional) ───
		{Type: "aws_sqs_queue", Label: "SQS Queue", Icon: "📬", Category: "Messaging", Provider: "aws",
			Defaults: map[string]any{"name": "my-queue", "visibility_timeout_seconds": 30, "message_retention_seconds": 345600},
		},
		{Type: "aws_sns_topic_subscription", Label: "SNS Subscription", Icon: "📨", Category: "Messaging", Provider: "aws",
			Defaults:    map[string]any{"protocol": "email", "endpoint": "ops@example.com"},
			ConnectsTo:  []string{"aws_sns_topic"},
			ConnectsVia: map[string]string{"topic_arn": "aws_sns_topic"},
		},
		{Type: "aws_kinesis_stream", Label: "Kinesis Stream", Icon: "🌊", Category: "Messaging", Provider: "aws",
			Defaults: map[string]any{"name": "my-stream", "shard_count": 1},
		},
		{Type: "aws_mq_broker", Label: "Amazon MQ", Icon: "📮", Category: "Messaging", Provider: "aws",
			Defaults: map[string]any{"broker_name": "my-broker", "engine_type": "ActiveMQ", "engine_version": "5.17.6", "host_instance_type": "mq.t3.micro"},
		},

		// ─── Data & Analytics ───
		{Type: "aws_glue_catalog_database", Label: "Glue Database", Icon: "📚", Category: "Data", Provider: "aws",
			Defaults: map[string]any{"name": "my-glue-db"},
		},
		{Type: "aws_athena_workgroup", Label: "Athena Workgroup", Icon: "🔍", Category: "Data", Provider: "aws",
			Defaults: map[string]any{"name": "my-workgroup"},
		},
		{Type: "aws_emr_cluster", Label: "EMR Cluster", Icon: "⚙️", Category: "Data", Provider: "aws",
			Defaults: map[string]any{"name": "my-emr", "release_label": "emr-7.0.0"},
		},
		{Type: "aws_sagemaker_notebook_instance", Label: "SageMaker Notebook", Icon: "📓", Category: "Data", Provider: "aws",
			Defaults: map[string]any{"name": "my-notebook", "instance_type": "ml.t3.medium"},
		},

		// ─── CI/CD ───
		{Type: "aws_codebuild_project", Label: "CodeBuild", Icon: "🏗️", Category: "CI/CD", Provider: "aws",
			Defaults: map[string]any{"name": "my-build"},
		},
		{Type: "aws_codepipeline", Label: "CodePipeline", Icon: "🔄", Category: "CI/CD", Provider: "aws",
			Defaults: map[string]any{"name": "my-pipeline"},
		},
		{Type: "aws_codecommit_repository", Label: "CodeCommit", Icon: "📥", Category: "CI/CD", Provider: "aws",
			Defaults: map[string]any{"repository_name": "my-repo"},
		},

		// ─── Step Functions & EventBridge ───
		{Type: "aws_sfn_state_machine", Label: "Step Functions", Icon: "🔀", Category: "Integration", Provider: "aws",
			Defaults:    map[string]any{"name": "my-state-machine"},
			ConnectsTo:  []string{"aws_iam_role"},
			ConnectsVia: map[string]string{"role_arn": "aws_iam_role"},
		},
		{Type: "aws_cloudwatch_event_rule", Label: "EventBridge Rule", Icon: "📅", Category: "Integration", Provider: "aws",
			Defaults: map[string]any{"name": "my-rule", "schedule_expression": "rate(5 minutes)"},
		},
	}
}
