package catalog

func gcpResources() []Resource {
	return []Resource{
		// ─── Networking ───
		{Type: "google_compute_network", Label: "VPC Network", Icon: "🌐", Category: "Networking", Provider: "google",
			Defaults: map[string]any{"name": "my-vpc", "auto_create_subnetworks": false},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "auto_create_subnetworks", Type: "bool", Default: false, Description: "Auto-create subnets in each region"},
				{Name: "routing_mode", Type: "select", Default: "REGIONAL", Options: []string{"REGIONAL", "GLOBAL"}},
			},
		},
		{Type: "google_compute_subnetwork", Label: "Subnet", Icon: "📡", Category: "Networking", Provider: "google",
			Defaults: map[string]any{"name": "my-subnet", "ip_cidr_range": "10.0.1.0/24", "region": "us-central1"},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "ip_cidr_range", Type: "string", Required: true, Default: "10.0.1.0/24"},
				{Name: "region", Type: "select", Default: "us-central1", Options: []string{"us-central1", "us-east1", "us-west1", "europe-west1", "asia-east1"}},
				{Name: "private_ip_google_access", Type: "bool", Default: true},
			},
			ConnectsTo:  []string{"google_compute_network"},
			ConnectsVia: map[string]string{"network": "google_compute_network"},
		},
		{Type: "google_compute_router", Label: "Cloud Router", Icon: "🔄", Category: "Networking", Provider: "google",
			Defaults:    map[string]any{"name": "my-router", "region": "us-central1"},
			ConnectsTo:  []string{"google_compute_network"},
			ConnectsVia: map[string]string{"network": "google_compute_network"},
		},
		{Type: "google_compute_router_nat", Label: "Cloud NAT", Icon: "🔀", Category: "Networking", Provider: "google",
			Defaults:    map[string]any{"name": "my-nat", "nat_ip_allocate_option": "AUTO_ONLY", "source_subnetwork_ip_ranges_to_nat": "ALL_SUBNETWORKS_ALL_IP_RANGES"},
			ConnectsTo:  []string{"google_compute_router"},
			ConnectsVia: map[string]string{"router": "google_compute_router"},
		},
		{Type: "google_compute_firewall", Label: "Firewall Rule", Icon: "🧱", Category: "Networking", Provider: "google",
			Defaults: map[string]any{"name": "allow-http", "direction": "INGRESS"},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "direction", Type: "select", Default: "INGRESS", Options: []string{"INGRESS", "EGRESS"}},
				{Name: "priority", Type: "number", Default: 1000},
			},
			ConnectsTo:  []string{"google_compute_network"},
			ConnectsVia: map[string]string{"network": "google_compute_network"},
		},
		{Type: "google_compute_address", Label: "Static IP", Icon: "📌", Category: "Networking", Provider: "google",
			Defaults: map[string]any{"name": "my-ip", "region": "us-central1"},
		},
		{Type: "google_compute_global_address", Label: "Global Static IP", Icon: "🌍", Category: "Networking", Provider: "google",
			Defaults: map[string]any{"name": "my-global-ip"},
		},
		{Type: "google_dns_managed_zone", Label: "Cloud DNS Zone", Icon: "🌐", Category: "Networking", Provider: "google",
			Defaults: map[string]any{"name": "my-zone", "dns_name": "example.com."},
		},
		{Type: "google_dns_record_set", Label: "DNS Record", Icon: "📝", Category: "Networking", Provider: "google",
			Defaults:    map[string]any{"name": "www.example.com.", "type": "A", "ttl": 300},
			ConnectsTo:  []string{"google_dns_managed_zone"},
			ConnectsVia: map[string]string{"managed_zone": "google_dns_managed_zone"},
		},
		{Type: "google_compute_vpn_gateway", Label: "VPN Gateway", Icon: "🔒", Category: "Networking", Provider: "google",
			Defaults:    map[string]any{"name": "my-vpn-gw", "region": "us-central1"},
			ConnectsTo:  []string{"google_compute_network"},
			ConnectsVia: map[string]string{"network": "google_compute_network"},
		},

		// ─── Compute ───
		{Type: "google_compute_instance", Label: "VM Instance", Icon: "🖥️", Category: "Compute", Provider: "google",
			Defaults: map[string]any{"name": "my-vm", "machine_type": "e2-medium", "zone": "us-central1-a"},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "machine_type", Type: "select", Required: true, Default: "e2-medium",
					Options: []string{"e2-micro", "e2-small", "e2-medium", "e2-standard-2", "e2-standard-4", "n2-standard-2", "n2-standard-4", "n2-standard-8", "c2-standard-4"}},
				{Name: "zone", Type: "select", Default: "us-central1-a", Options: []string{"us-central1-a", "us-central1-b", "us-east1-b", "us-west1-a", "europe-west1-b"}},
			},
			ConnectsTo:  []string{"google_compute_subnetwork"},
			ConnectsVia: map[string]string{"subnetwork": "google_compute_subnetwork"},
		},
		{Type: "google_compute_instance_template", Label: "Instance Template", Icon: "📋", Category: "Compute", Provider: "google",
			Defaults: map[string]any{"name_prefix": "tpl-", "machine_type": "e2-medium"},
		},
		{Type: "google_compute_instance_group_manager", Label: "Managed Instance Group", Icon: "👥", Category: "Compute", Provider: "google",
			Defaults: map[string]any{"name": "my-mig", "base_instance_name": "app", "zone": "us-central1-a", "target_size": 2},
		},
		{Type: "google_container_cluster", Label: "GKE Cluster", Icon: "☸️", Category: "Compute", Provider: "google",
			Defaults: map[string]any{"name": "my-gke", "location": "us-central1", "initial_node_count": 3, "remove_default_node_pool": true},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "location", Type: "select", Default: "us-central1", Options: []string{"us-central1", "us-east1", "us-west1", "europe-west1", "asia-east1"}},
				{Name: "initial_node_count", Type: "number", Default: 3},
				{Name: "remove_default_node_pool", Type: "bool", Default: true},
			},
			ConnectsTo:  []string{"google_compute_network", "google_compute_subnetwork"},
			ConnectsVia: map[string]string{"network": "google_compute_network", "subnetwork": "google_compute_subnetwork"},
		},
		{Type: "google_container_node_pool", Label: "GKE Node Pool", Icon: "🏊", Category: "Compute", Provider: "google",
			Defaults:    map[string]any{"name": "default-pool", "node_count": 3},
			ConnectsTo:  []string{"google_container_cluster"},
			ConnectsVia: map[string]string{"cluster": "google_container_cluster"},
		},
		{Type: "google_cloud_run_service", Label: "Cloud Run", Icon: "🚀", Category: "Compute", Provider: "google",
			Defaults: map[string]any{"name": "my-service", "location": "us-central1"},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "location", Type: "select", Default: "us-central1", Options: []string{"us-central1", "us-east1", "us-west1", "europe-west1"}},
			},
		},
		{Type: "google_cloudfunctions_function", Label: "Cloud Function", Icon: "⚡", Category: "Compute", Provider: "google",
			Defaults: map[string]any{"name": "my-function", "runtime": "nodejs20", "entry_point": "helloWorld", "available_memory_mb": 256},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "runtime", Type: "select", Default: "nodejs20", Options: []string{"nodejs20", "nodejs18", "python312", "python311", "go122", "java17", "ruby32"}},
				{Name: "entry_point", Type: "string", Required: true},
				{Name: "available_memory_mb", Type: "number", Default: 256},
			},
		},
		{Type: "google_app_engine_application", Label: "App Engine", Icon: "🌐", Category: "Compute", Provider: "google",
			Defaults: map[string]any{"location_id": "us-central"},
		},

		// ─── Storage ───
		{Type: "google_storage_bucket", Label: "Cloud Storage Bucket", Icon: "🪣", Category: "Storage", Provider: "google",
			Defaults: map[string]any{"name": "my-bucket", "location": "US", "force_destroy": false, "uniform_bucket_level_access": true},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true, Description: "Globally unique bucket name"},
				{Name: "location", Type: "select", Default: "US", Options: []string{"US", "EU", "ASIA", "US-CENTRAL1", "US-EAST1", "EUROPE-WEST1"}},
				{Name: "storage_class", Type: "select", Default: "STANDARD", Options: []string{"STANDARD", "NEARLINE", "COLDLINE", "ARCHIVE"}},
				{Name: "force_destroy", Type: "bool", Default: false},
				{Name: "uniform_bucket_level_access", Type: "bool", Default: true},
			},
		},
		{Type: "google_compute_disk", Label: "Persistent Disk", Icon: "💾", Category: "Storage", Provider: "google",
			Defaults: map[string]any{"name": "my-disk", "size": 50, "type": "pd-ssd", "zone": "us-central1-a"},
		},
		{Type: "google_filestore_instance", Label: "Filestore", Icon: "📁", Category: "Storage", Provider: "google",
			Defaults: map[string]any{"name": "my-filestore", "tier": "BASIC_HDD", "zone": "us-central1-a"},
		},

		// ─── Database ───
		{Type: "google_sql_database_instance", Label: "Cloud SQL", Icon: "🗄️", Category: "Database", Provider: "google",
			Defaults: map[string]any{"name": "my-db", "database_version": "POSTGRES_15", "region": "us-central1", "deletion_protection": false},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "database_version", Type: "select", Default: "POSTGRES_15", Options: []string{"POSTGRES_15", "POSTGRES_14", "MYSQL_8_0", "MYSQL_5_7", "SQLSERVER_2019_STANDARD"}},
				{Name: "region", Type: "select", Default: "us-central1", Options: []string{"us-central1", "us-east1", "us-west1", "europe-west1"}},
				{Name: "deletion_protection", Type: "bool", Default: false},
			},
		},
		{Type: "google_sql_database", Label: "SQL Database", Icon: "📊", Category: "Database", Provider: "google",
			Defaults:    map[string]any{"name": "mydb"},
			ConnectsTo:  []string{"google_sql_database_instance"},
			ConnectsVia: map[string]string{"instance": "google_sql_database_instance"},
		},
		{Type: "google_redis_instance", Label: "Memorystore Redis", Icon: "⚡", Category: "Database", Provider: "google",
			Defaults: map[string]any{"name": "my-redis", "tier": "BASIC", "memory_size_gb": 1, "region": "us-central1"},
		},
		{Type: "google_spanner_instance", Label: "Cloud Spanner", Icon: "🌍", Category: "Database", Provider: "google",
			Defaults: map[string]any{"name": "my-spanner", "num_nodes": 1, "display_name": "My Spanner"},
		},
		{Type: "google_firestore_database", Label: "Firestore", Icon: "🔥", Category: "Database", Provider: "google",
			Defaults: map[string]any{"name": "(default)", "location_id": "us-central", "type": "FIRESTORE_NATIVE"},
		},
		{Type: "google_bigtable_instance", Label: "Bigtable", Icon: "📈", Category: "Database", Provider: "google",
			Defaults: map[string]any{"name": "my-bigtable", "display_name": "My Bigtable"},
		},

		// ─── Security & IAM ───
		{Type: "google_service_account", Label: "Service Account", Icon: "🔑", Category: "Security", Provider: "google",
			Defaults: map[string]any{"account_id": "my-sa", "display_name": "My Service Account"},
		},
		{Type: "google_project_iam_member", Label: "IAM Binding", Icon: "📜", Category: "Security", Provider: "google",
			Defaults: map[string]any{"role": "roles/viewer"},
		},
		{Type: "google_kms_key_ring", Label: "KMS Key Ring", Icon: "🔐", Category: "Security", Provider: "google",
			Defaults: map[string]any{"name": "my-keyring", "location": "us-central1"},
		},
		{Type: "google_kms_crypto_key", Label: "KMS Crypto Key", Icon: "🔐", Category: "Security", Provider: "google",
			Defaults:    map[string]any{"name": "my-key", "rotation_period": "7776000s"},
			ConnectsTo:  []string{"google_kms_key_ring"},
			ConnectsVia: map[string]string{"key_ring": "google_kms_key_ring"},
		},
		{Type: "google_secret_manager_secret", Label: "Secret Manager", Icon: "🤫", Category: "Security", Provider: "google",
			Defaults: map[string]any{"secret_id": "my-secret"},
		},

		// ─── Load Balancing ───
		{Type: "google_compute_backend_service", Label: "Backend Service", Icon: "⚖️", Category: "Load Balancing", Provider: "google",
			Defaults: map[string]any{"name": "my-backend", "protocol": "HTTP", "port_name": "http"},
		},
		{Type: "google_compute_url_map", Label: "URL Map", Icon: "🗺️", Category: "Load Balancing", Provider: "google",
			Defaults:    map[string]any{"name": "my-url-map"},
			ConnectsTo:  []string{"google_compute_backend_service"},
			ConnectsVia: map[string]string{"default_service": "google_compute_backend_service"},
		},
		{Type: "google_compute_target_http_proxy", Label: "HTTP Proxy", Icon: "🔀", Category: "Load Balancing", Provider: "google",
			Defaults:    map[string]any{"name": "my-http-proxy"},
			ConnectsTo:  []string{"google_compute_url_map"},
			ConnectsVia: map[string]string{"url_map": "google_compute_url_map"},
		},
		{Type: "google_compute_global_forwarding_rule", Label: "Forwarding Rule", Icon: "➡️", Category: "Load Balancing", Provider: "google",
			Defaults:    map[string]any{"name": "my-fwd-rule", "port_range": "80"},
			ConnectsTo:  []string{"google_compute_target_http_proxy"},
			ConnectsVia: map[string]string{"target": "google_compute_target_http_proxy"},
		},
		{Type: "google_compute_health_check", Label: "Health Check", Icon: "❤️", Category: "Load Balancing", Provider: "google",
			Defaults: map[string]any{"name": "my-health-check", "check_interval_sec": 10, "timeout_sec": 5},
		},

		// ─── Monitoring ───
		{Type: "google_logging_metric", Label: "Log Metric", Icon: "📋", Category: "Monitoring", Provider: "google",
			Defaults: map[string]any{"name": "error-count", "filter": "severity>=ERROR"},
		},
		{Type: "google_monitoring_alert_policy", Label: "Alert Policy", Icon: "🚨", Category: "Monitoring", Provider: "google",
			Defaults: map[string]any{"display_name": "High Error Rate", "combiner": "OR"},
		},
		{Type: "google_monitoring_notification_channel", Label: "Notification Channel", Icon: "📢", Category: "Monitoring", Provider: "google",
			Defaults: map[string]any{"display_name": "Ops Team Email", "type": "email"},
		},

		// ─── Pub/Sub & Messaging ───
		{Type: "google_pubsub_topic", Label: "Pub/Sub Topic", Icon: "📬", Category: "Messaging", Provider: "google",
			Defaults: map[string]any{"name": "my-topic"},
		},
		{Type: "google_pubsub_subscription", Label: "Pub/Sub Subscription", Icon: "📨", Category: "Messaging", Provider: "google",
			Defaults:    map[string]any{"name": "my-sub", "ack_deadline_seconds": 20},
			ConnectsTo:  []string{"google_pubsub_topic"},
			ConnectsVia: map[string]string{"topic": "google_pubsub_topic"},
		},

		// ─── Data & Analytics ───
		{Type: "google_bigquery_dataset", Label: "BigQuery Dataset", Icon: "📊", Category: "Data", Provider: "google",
			Defaults: map[string]any{"dataset_id": "my_dataset", "location": "US"},
		},
		{Type: "google_bigquery_table", Label: "BigQuery Table", Icon: "📋", Category: "Data", Provider: "google",
			Defaults:    map[string]any{"table_id": "my_table"},
			ConnectsTo:  []string{"google_bigquery_dataset"},
			ConnectsVia: map[string]string{"dataset_id": "google_bigquery_dataset"},
		},
		{Type: "google_dataflow_job", Label: "Dataflow Job", Icon: "🌊", Category: "Data", Provider: "google",
			Defaults: map[string]any{"name": "my-job", "template_gcs_path": "gs://dataflow-templates/latest/Word_Count"},
		},
		{Type: "google_dataproc_cluster", Label: "Dataproc Cluster", Icon: "⚙️", Category: "Data", Provider: "google",
			Defaults: map[string]any{"name": "my-dataproc", "region": "us-central1"},
		},
	}
}
