package catalog

// ansibleExtraResources returns Ansible modules beyond the base set.
func ansibleExtraResources() []Resource {
	return []Resource{
		// ─── Packages (additional) ───
		{Type: "dnf", Label: "Install Package (dnf)", Icon: "📦", Category: "Packages",
			Defaults: map[string]any{"name": "httpd", "state": "present"},
			Fields: []Field{
				{Name: "name", Type: "string", Required: true},
				{Name: "state", Type: "select", Default: "present", Options: []string{"present", "absent", "latest", "installed", "removed"}},
			},
		},
		{Type: "snap", Label: "Snap Package", Icon: "📦", Category: "Packages",
			Defaults: map[string]any{"name": "certbot", "classic": true},
		},
		{Type: "npm", Label: "NPM Package", Icon: "📦", Category: "Packages",
			Defaults: map[string]any{"name": "pm2", "global": true, "state": "present"},
		},
		{Type: "gem", Label: "Ruby Gem", Icon: "💎", Category: "Packages",
			Defaults: map[string]any{"name": "bundler", "state": "present"},
		},
		{Type: "package", Label: "Generic Package", Icon: "📦", Category: "Packages",
			Defaults: map[string]any{"name": "curl", "state": "present"},
		},
		{Type: "apt_repository", Label: "APT Repository", Icon: "📋", Category: "Packages",
			Defaults: map[string]any{"repo": "ppa:deadsnakes/ppa", "state": "present"},
		},
		{Type: "apt_key", Label: "APT Key", Icon: "🔑", Category: "Packages",
			Defaults: map[string]any{"url": "https://example.com/key.gpg", "state": "present"},
		},

		// ─── System (additional) ───
		{Type: "hostname", Label: "Set Hostname", Icon: "🏷️", Category: "System",
			Defaults: map[string]any{"name": "my-server"},
		},
		{Type: "timezone", Label: "Set Timezone", Icon: "🕐", Category: "System",
			Defaults: map[string]any{"name": "UTC"},
		},
		{Type: "locale_gen", Label: "Generate Locale", Icon: "🌍", Category: "System",
			Defaults: map[string]any{"name": "en_US.UTF-8", "state": "present"},
		},
		{Type: "reboot", Label: "Reboot Server", Icon: "🔄", Category: "System",
			Defaults: map[string]any{"reboot_timeout": 300, "msg": "Reboot initiated by Ansible"},
		},
		{Type: "mount", Label: "Mount Filesystem", Icon: "💾", Category: "System",
			Defaults: map[string]any{"path": "/mnt/data", "src": "/dev/sdb1", "fstype": "ext4", "state": "mounted"},
		},
		{Type: "modprobe", Label: "Kernel Module", Icon: "🧩", Category: "System",
			Defaults: map[string]any{"name": "br_netfilter", "state": "present"},
		},
		{Type: "selinux", Label: "SELinux", Icon: "🛡️", Category: "System",
			Defaults: map[string]any{"state": "enforcing", "policy": "targeted"},
		},
		{Type: "authorized_key", Label: "SSH Authorized Key", Icon: "🔑", Category: "System",
			Defaults: map[string]any{"user": "deploy", "state": "present", "key": "ssh-rsa AAAA..."},
			Fields: []Field{
				{Name: "user", Type: "string", Required: true},
				{Name: "key", Type: "string", Required: true, Description: "SSH public key"},
				{Name: "state", Type: "select", Default: "present", Options: []string{"present", "absent"}},
			},
		},
		{Type: "openssh_keypair", Label: "Generate SSH Key", Icon: "🔐", Category: "System",
			Defaults: map[string]any{"path": "/home/deploy/.ssh/id_ed25519", "type": "ed25519"},
		},

		// ─── Files (additional) ───
		{Type: "blockinfile", Label: "Block in File", Icon: "📝", Category: "Files",
			Defaults: map[string]any{"path": "/etc/config", "block": "key1=value1\nkey2=value2", "marker": "# {mark} ANSIBLE MANAGED BLOCK"},
		},
		{Type: "synchronize", Label: "Rsync Files", Icon: "🔄", Category: "Files",
			Defaults: map[string]any{"src": "/local/path/", "dest": "/remote/path/", "mode": "push"},
		},
		{Type: "fetch", Label: "Fetch from Remote", Icon: "📥", Category: "Files",
			Defaults: map[string]any{"src": "/var/log/app.log", "dest": "/tmp/fetched/", "flat": true},
		},
		{Type: "stat", Label: "File Status", Icon: "📊", Category: "Files",
			Defaults: map[string]any{"path": "/etc/myfile"},
		},
		{Type: "find", Label: "Find Files", Icon: "🔍", Category: "Files",
			Defaults: map[string]any{"paths": "/var/log", "patterns": "*.log", "age": "7d"},
		},
		{Type: "acl", Label: "File ACL", Icon: "🛡️", Category: "Files",
			Defaults: map[string]any{"path": "/opt/shared", "entity": "deploy", "etype": "user", "permissions": "rwx", "state": "present"},
		},

		// ─── Containers (additional) ───
		{Type: "docker_volume", Label: "Docker Volume", Icon: "💾", Category: "Containers",
			Defaults: map[string]any{"name": "app-data", "state": "present"},
		},
		{Type: "docker_login", Label: "Docker Login", Icon: "🔑", Category: "Containers",
			Defaults: map[string]any{"registry_url": "https://index.docker.io/v1/", "username": "myuser"},
		},
		{Type: "docker_swarm", Label: "Docker Swarm", Icon: "🐝", Category: "Containers",
			Defaults: map[string]any{"state": "present"},
		},
		{Type: "k8s", Label: "Kubernetes Resource", Icon: "☸️", Category: "Containers",
			Defaults: map[string]any{"state": "present", "definition": ""},
			Fields: []Field{
				{Name: "state", Type: "select", Default: "present", Options: []string{"present", "absent"}},
				{Name: "src", Type: "string", Description: "Path to YAML manifest"},
				{Name: "namespace", Type: "string", Default: "default"},
			},
		},
		{Type: "helm", Label: "Helm Chart", Icon: "⛵", Category: "Containers",
			Defaults: map[string]any{"name": "my-release", "chart_ref": "stable/nginx", "release_namespace": "default"},
		},

		// ─── Networking (additional) ───
		{Type: "firewalld", Label: "Firewalld Rule", Icon: "🧱", Category: "Networking",
			Defaults: map[string]any{"service": "http", "permanent": true, "state": "enabled"},
			Fields: []Field{
				{Name: "service", Type: "string"},
				{Name: "port", Type: "string", Description: "e.g., 8080/tcp"},
				{Name: "permanent", Type: "bool", Default: true},
				{Name: "state", Type: "select", Default: "enabled", Options: []string{"enabled", "disabled"}},
			},
		},
		{Type: "nmcli", Label: "Network Manager", Icon: "🌐", Category: "Networking",
			Defaults: map[string]any{"conn_name": "eth0", "type": "ethernet", "state": "present"},
		},
		{Type: "uri", Label: "HTTP Request", Icon: "🌐", Category: "Networking",
			Defaults: map[string]any{"url": "https://api.example.com/health", "method": "GET", "status_code": 200},
		},
		{Type: "wait_for", Label: "Wait for Port", Icon: "⏳", Category: "Networking",
			Defaults: map[string]any{"host": "localhost", "port": 8080, "timeout": 300},
		},
		{Type: "get_url", Label: "Download File", Icon: "⬇️", Category: "Networking",
			Defaults: map[string]any{"url": "https://example.com/file.tar.gz", "dest": "/tmp/file.tar.gz", "mode": "0644"},
		},

		// ─── Cloud (additional) ───
		{Type: "amazon.aws.ec2_instance", Label: "AWS EC2 (collection)", Icon: "☁️", Category: "Cloud",
			Defaults: map[string]any{"instance_type": "t3.micro", "image_id": "ami-0c55b159cbfafe1f0", "state": "running", "wait": true},
		},
		{Type: "amazon.aws.s3_bucket", Label: "AWS S3 (collection)", Icon: "🪣", Category: "Cloud",
			Defaults: map[string]any{"name": "my-bucket", "state": "present"},
		},
		{Type: "amazon.aws.ec2_vpc_net", Label: "AWS VPC (collection)", Icon: "🌐", Category: "Cloud",
			Defaults: map[string]any{"name": "my-vpc", "cidr_block": "10.0.0.0/16", "state": "present"},
		},
		{Type: "amazon.aws.rds_instance", Label: "AWS RDS (collection)", Icon: "🗄️", Category: "Cloud",
			Defaults: map[string]any{"db_instance_identifier": "mydb", "engine": "postgres", "instance_type": "db.t3.micro"},
		},
		{Type: "google.cloud.gcp_compute_instance", Label: "GCP VM (collection)", Icon: "☁️", Category: "Cloud",
			Defaults: map[string]any{"name": "my-instance", "machine_type": "e2-micro", "zone": "us-central1-a", "state": "present"},
		},
		{Type: "google.cloud.gcp_compute_network", Label: "GCP VPC (collection)", Icon: "🌐", Category: "Cloud",
			Defaults: map[string]any{"name": "my-network", "auto_create_subnetworks": false, "state": "present"},
		},
		{Type: "google.cloud.gcp_storage_bucket", Label: "GCP Storage (collection)", Icon: "🪣", Category: "Cloud",
			Defaults: map[string]any{"name": "my-bucket", "location": "US", "state": "present"},
		},
		{Type: "azure.azcollection.azure_rm_virtualmachine", Label: "Azure VM (collection)", Icon: "☁️", Category: "Cloud",
			Defaults: map[string]any{"name": "my-vm", "resource_group": "my-rg", "vm_size": "Standard_B2s"},
		},
		{Type: "azure.azcollection.azure_rm_storageaccount", Label: "Azure Storage (collection)", Icon: "🪣", Category: "Cloud",
			Defaults: map[string]any{"name": "mystorageacct", "resource_group": "my-rg", "account_type": "Standard_LRS"},
		},
		{Type: "azure.azcollection.azure_rm_virtualnetwork", Label: "Azure VNet (collection)", Icon: "🌐", Category: "Cloud",
			Defaults: map[string]any{"name": "my-vnet", "resource_group": "my-rg", "address_prefixes_cidr": "10.0.0.0/16"},
		},

		// ─── Database ───
		{Type: "mysql_db", Label: "MySQL Database", Icon: "🐬", Category: "Database",
			Defaults: map[string]any{"name": "mydb", "state": "present"},
		},
		{Type: "mysql_user", Label: "MySQL User", Icon: "👤", Category: "Database",
			Defaults: map[string]any{"name": "appuser", "password": "changeme", "priv": "mydb.*:ALL", "state": "present"},
		},
		{Type: "postgresql_db", Label: "PostgreSQL Database", Icon: "🐘", Category: "Database",
			Defaults: map[string]any{"name": "mydb", "state": "present"},
		},
		{Type: "postgresql_user", Label: "PostgreSQL User", Icon: "👤", Category: "Database",
			Defaults: map[string]any{"name": "appuser", "password": "changeme", "state": "present"},
		},
		{Type: "redis", Label: "Redis Command", Icon: "⚡", Category: "Database",
			Defaults: map[string]any{"command": "SET", "key": "mykey", "value": "myvalue"},
		},
		{Type: "mongodb_user", Label: "MongoDB User", Icon: "🍃", Category: "Database",
			Defaults: map[string]any{"database": "admin", "name": "appuser", "password": "changeme", "state": "present"},
		},

		// ─── Web Servers ───
		{Type: "nginx_site", Label: "Nginx Site Config", Icon: "🌐", Category: "Web",
			Defaults: map[string]any{"name": "myapp", "state": "present"},
		},
		{Type: "apache2_module", Label: "Apache Module", Icon: "🌐", Category: "Web",
			Defaults: map[string]any{"name": "rewrite", "state": "present"},
		},

		// ─── Security (additional) ───
		{Type: "openssl_certificate", Label: "TLS Certificate", Icon: "📜", Category: "Security",
			Defaults: map[string]any{"path": "/etc/ssl/certs/myapp.pem", "privatekey_path": "/etc/ssl/private/myapp.key", "provider": "selfsigned"},
		},
		{Type: "openssl_privatekey", Label: "TLS Private Key", Icon: "🔐", Category: "Security",
			Defaults: map[string]any{"path": "/etc/ssl/private/myapp.key", "size": 4096},
		},
		{Type: "community.crypto.x509_certificate", Label: "X.509 Certificate", Icon: "📜", Category: "Security",
			Defaults: map[string]any{"path": "/etc/ssl/certs/myapp.pem", "provider": "selfsigned"},
		},

		// ─── Commands (additional) ───
		{Type: "raw", Label: "Raw Command (no Python)", Icon: "⚡", Category: "Commands",
			Defaults: map[string]any{"cmd": "apt-get install -y python3"},
		},
		{Type: "script", Label: "Run Local Script", Icon: "📜", Category: "Commands",
			Defaults: map[string]any{"cmd": "scripts/setup.sh"},
		},
		{Type: "expect", Label: "Expect (interactive)", Icon: "💬", Category: "Commands",
			Defaults: map[string]any{"command": "passwd deploy", "responses": ""},
		},

		// ─── Misc / Debug ───
		{Type: "debug", Label: "Debug Output", Icon: "🐛", Category: "Debug",
			Defaults: map[string]any{"msg": "Variable value: {{ my_var }}"},
		},
		{Type: "assert", Label: "Assert Condition", Icon: "✅", Category: "Debug",
			Defaults: map[string]any{"that": "result.rc == 0", "fail_msg": "Command failed"},
		},
		{Type: "fail", Label: "Fail with Message", Icon: "❌", Category: "Debug",
			Defaults: map[string]any{"msg": "This should not happen"},
		},
		{Type: "set_fact", Label: "Set Variable", Icon: "📝", Category: "Debug",
			Defaults: map[string]any{"my_var": "my_value"},
		},
		{Type: "pause", Label: "Pause Execution", Icon: "⏸️", Category: "Debug",
			Defaults: map[string]any{"seconds": 10, "prompt": "Press enter to continue"},
		},
		{Type: "include_role", Label: "Include Role", Icon: "📂", Category: "Flow",
			Defaults: map[string]any{"name": "common"},
		},
		{Type: "import_tasks", Label: "Import Tasks", Icon: "📥", Category: "Flow",
			Defaults: map[string]any{"file": "tasks/setup.yml"},
		},
		{Type: "include_tasks", Label: "Include Tasks", Icon: "📋", Category: "Flow",
			Defaults: map[string]any{"file": "tasks/deploy.yml"},
		},
	}
}
