package drift

import (
	"encoding/json"
	"strings"
	"testing"
	"time"
)

func TestRenderRemediationArtifacts(t *testing.T) {
	createdAt := time.Date(2026, 6, 9, 19, 0, 0, 0, time.UTC)
	proposal := RemediationProposal{
		Mode:          RemediationModeRevert,
		Title:         "Revert unauthorized drift for demo",
		Branch:        "iac-studio-drift-revert-demo",
		CommitMessage: "Document drift revert for demo",
		Body:          "## Summary\n- Mode: `revert`\n",
		Findings: []DriftFinding{
			{Address: "aws_security_group.web", Classification: ClassificationUnauthorizedChange},
		},
		FileChanges: []RemediationFileChange{
			{Path: "main.tf", Action: "revert", Address: "aws_security_group.web", Summary: "Restore ingress."},
		},
	}

	set, rendered, err := RenderRemediationArtifacts(proposal, createdAt)
	if err != nil {
		t.Fatalf("RenderRemediationArtifacts: %v", err)
	}
	if set.ID != "iac-studio-drift-revert-demo" {
		t.Fatalf("id = %q", set.ID)
	}
	if set.Root != ".iac-studio/remediations/iac-studio-drift-revert-demo" {
		t.Fatalf("root = %q", set.Root)
	}
	if len(set.Files) != 3 || len(rendered) != 3 {
		t.Fatalf("files = %d/%d, want 3/3", len(set.Files), len(rendered))
	}

	contents := map[string]string{}
	for _, file := range rendered {
		contents[file.Path] = file.Content
		if file.Size == 0 {
			t.Fatalf("rendered file %s has zero size", file.Path)
		}
	}
	runbook := contents[".iac-studio/remediations/iac-studio-drift-revert-demo/README.md"]
	if !strings.Contains(runbook, "Generated by IaC Studio") ||
		!strings.Contains(runbook, "Run drift again after remediation") {
		t.Fatalf("runbook missing expected guidance:\n%s", runbook)
	}
	if contents[".iac-studio/remediations/iac-studio-drift-revert-demo/pr-body.md"] != proposal.Body {
		t.Fatalf("pr-body artifact should match proposal body")
	}

	var metadata struct {
		ID       string              `json:"id"`
		Root     string              `json:"root"`
		Proposal RemediationProposal `json:"proposal"`
		Files    []struct {
			Path string `json:"path"`
			Kind string `json:"kind"`
		} `json:"files"`
	}
	if err := json.Unmarshal([]byte(contents[".iac-studio/remediations/iac-studio-drift-revert-demo/proposal.json"]), &metadata); err != nil {
		t.Fatalf("metadata is not valid json: %v", err)
	}
	if metadata.ID != set.ID || metadata.Root != set.Root || metadata.Proposal.Title != proposal.Title {
		t.Fatalf("unexpected metadata: %#v", metadata)
	}
	if len(metadata.Files) != 3 || metadata.Files[2].Kind != "metadata" {
		t.Fatalf("metadata should list all files: %#v", metadata.Files)
	}
}

func TestRenderRemediationArtifactsRejectsInvalidProposal(t *testing.T) {
	_, _, err := RenderRemediationArtifacts(RemediationProposal{
		Mode:  "manual",
		Title: "Manual drift",
	}, time.Time{})
	if err == nil {
		t.Fatal("expected invalid mode error")
	}

	_, _, err = RenderRemediationArtifacts(RemediationProposal{
		Mode: RemediationModeCodify,
	}, time.Time{})
	if err == nil {
		t.Fatal("expected missing title error")
	}
}
