package drift

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"
)

const remediationArtifactRoot = ".iac-studio/remediations"

// RemediationArtifactSet describes generated review artifacts for a drift
// remediation proposal. The files are commit-ready project files, not cloud
// mutations.
type RemediationArtifactSet struct {
	ID        string                    `json:"id"`
	Root      string                    `json:"root"`
	CreatedAt time.Time                 `json:"created_at"`
	Proposal  RemediationProposal       `json:"proposal"`
	Files     []RemediationArtifactFile `json:"files"`
}

// RemediationArtifactFile is a generated file summary returned to callers.
type RemediationArtifactFile struct {
	Path    string `json:"path"`
	Kind    string `json:"kind"`
	Summary string `json:"summary"`
	Size    int    `json:"size"`
}

// RenderedRemediationArtifact carries the content the API layer writes to disk.
type RenderedRemediationArtifact struct {
	RemediationArtifactFile
	Content string `json:"-"`
}

// RenderRemediationArtifacts turns a proposal into reviewable, commit-ready
// project files. It does not write to disk; callers own filesystem safety.
func RenderRemediationArtifacts(proposal RemediationProposal, createdAt time.Time) (RemediationArtifactSet, []RenderedRemediationArtifact, error) {
	if proposal.Mode != RemediationModeCodify && proposal.Mode != RemediationModeRevert {
		return RemediationArtifactSet{}, nil, errors.New("remediation proposal mode must be codify or revert")
	}
	if strings.TrimSpace(proposal.Title) == "" {
		return RemediationArtifactSet{}, nil, errors.New("remediation proposal title is required")
	}
	if createdAt.IsZero() {
		createdAt = time.Now().UTC()
	} else {
		createdAt = createdAt.UTC()
	}

	id := remediationArtifactID(proposal)
	root := remediationArtifactRoot + "/" + id
	rendered := []RenderedRemediationArtifact{
		{
			RemediationArtifactFile: RemediationArtifactFile{
				Path:    root + "/README.md",
				Kind:    "runbook",
				Summary: "Human-readable drift remediation runbook.",
			},
			Content: renderRemediationRunbook(proposal, createdAt),
		},
		{
			RemediationArtifactFile: RemediationArtifactFile{
				Path:    root + "/pr-body.md",
				Kind:    "pr_body",
				Summary: "Pull request body generated from the remediation proposal.",
			},
			Content: proposal.Body,
		},
	}

	metadataContent, err := renderRemediationMetadata(id, root, createdAt, proposal, rendered)
	if err != nil {
		return RemediationArtifactSet{}, nil, err
	}
	rendered = append(rendered, RenderedRemediationArtifact{
		RemediationArtifactFile: RemediationArtifactFile{
			Path:    root + "/proposal.json",
			Kind:    "metadata",
			Summary: "Machine-readable drift remediation proposal metadata.",
		},
		Content: metadataContent,
	})

	set := RemediationArtifactSet{
		ID:        id,
		Root:      root,
		CreatedAt: createdAt,
		Proposal:  proposal,
		Files:     make([]RemediationArtifactFile, 0, len(rendered)),
	}
	for i := range rendered {
		rendered[i].Size = len([]byte(rendered[i].Content))
		set.Files = append(set.Files, rendered[i].RemediationArtifactFile)
	}
	return set, rendered, nil
}

func remediationArtifactID(proposal RemediationProposal) string {
	if id := cleanArtifactSegment(proposal.Branch); id != "" {
		return id
	}
	if id := cleanArtifactSegment(proposal.Title); id != "" {
		return id
	}
	return "drift-remediation"
}

func cleanArtifactSegment(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	var out strings.Builder
	lastDash := false
	for _, r := range value {
		keep := (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9')
		if keep {
			out.WriteRune(r)
			lastDash = false
			continue
		}
		if !lastDash {
			out.WriteByte('-')
			lastDash = true
		}
	}
	return strings.Trim(out.String(), "-")
}

func renderRemediationRunbook(proposal RemediationProposal, createdAt time.Time) string {
	var b strings.Builder
	b.WriteString("# ")
	b.WriteString(proposal.Title)
	b.WriteString("\n\n")
	b.WriteString("Generated by IaC Studio for human review. This artifact does not apply infrastructure changes automatically.\n\n")
	b.WriteString("## PR metadata\n")
	b.WriteString(fmt.Sprintf("- Branch: `%s`\n", proposal.Branch))
	b.WriteString(fmt.Sprintf("- Commit message: `%s`\n", proposal.CommitMessage))
	b.WriteString(fmt.Sprintf("- Mode: `%s`\n", proposal.Mode))
	b.WriteString(fmt.Sprintf("- Generated: `%s`\n", createdAt.Format(time.RFC3339)))
	b.WriteString(fmt.Sprintf("- Findings: `%d`\n\n", len(proposal.Findings)))
	b.WriteString(proposal.Body)
	b.WriteString("\n\n## Review checklist\n")
	b.WriteString("- Confirm each finding still exists before opening a PR.\n")
	b.WriteString("- Run plan classification before applying any remediation.\n")
	b.WriteString("- Run policy and security checks after edits or provider-side remediation.\n")
	b.WriteString("- Run drift again after remediation to confirm the finding is resolved.\n")
	return b.String()
}

func renderRemediationMetadata(id, root string, createdAt time.Time, proposal RemediationProposal, rendered []RenderedRemediationArtifact) (string, error) {
	files := make([]RemediationArtifactFile, 0, len(rendered)+1)
	for _, file := range rendered {
		files = append(files, RemediationArtifactFile{
			Path:    file.Path,
			Kind:    file.Kind,
			Summary: file.Summary,
			Size:    len([]byte(file.Content)),
		})
	}
	files = append(files, RemediationArtifactFile{
		Path:    root + "/proposal.json",
		Kind:    "metadata",
		Summary: "Machine-readable drift remediation proposal metadata.",
	})
	payload := struct {
		ID        string                    `json:"id"`
		Root      string                    `json:"root"`
		CreatedAt time.Time                 `json:"created_at"`
		Proposal  RemediationProposal       `json:"proposal"`
		Files     []RemediationArtifactFile `json:"files"`
	}{
		ID:        id,
		Root:      root,
		CreatedAt: createdAt,
		Proposal:  proposal,
		Files:     files,
	}
	data, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return "", fmt.Errorf("rendering remediation metadata: %w", err)
	}
	return string(data) + "\n", nil
}
