package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/iac-studio/iac-studio/internal/parser"
)

// Generator produces IaC code from structured resources.
type Generator interface {
	Generate(resources []parser.Resource) (string, error)
	WriteScaffold(dir string) error
	FileExtension() string
}

// ForTool returns the appropriate generator.
func ForTool(tool string) Generator {
	switch tool {
	case "terraform", "opentofu":
		return &HCLGenerator{tool: tool}
	case "ansible":
		return &YAMLGenerator{}
	default:
		return &HCLGenerator{tool: "terraform"}
	}
}

// ─── HCL Generator (Terraform / OpenTofu) ───

type HCLGenerator struct {
	tool string
}

func (g *HCLGenerator) FileExtension() string { return ".tf" }

func (g *HCLGenerator) Generate(resources []parser.Resource) (string, error) {
	var b strings.Builder

	b.WriteString("# Generated by IaC Studio\n")
	b.WriteString("# Do not remove this comment — it enables bidirectional sync\n\n")
	b.WriteString("provider \"aws\" {\n  region = \"us-east-1\"\n}\n\n")

	for _, res := range resources {
		b.WriteString(fmt.Sprintf("resource \"%s\" \"%s\" {\n", res.Type, res.Name))
		for k, v := range res.Properties {
			switch val := v.(type) {
			case bool:
				b.WriteString(fmt.Sprintf("  %s = %t\n", k, val))
			case float64:
				b.WriteString(fmt.Sprintf("  %s = %g\n", k, val))
			case int:
				b.WriteString(fmt.Sprintf("  %s = %d\n", k, val))
			default:
				b.WriteString(fmt.Sprintf("  %s = \"%v\"\n", k, val))
			}
		}
		b.WriteString("}\n\n")
	}

	return b.String(), nil
}

func (g *HCLGenerator) WriteScaffold(dir string) error {
	files := map[string]string{
		"main.tf": fmt.Sprintf(`# %s project managed by IaC Studio

provider "aws" {
  region = var.region
}
`, g.tool),
		"variables.tf": `variable "region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "dev"
}
`,
		"outputs.tf": `# Outputs will be generated as resources are added
`,
		".gitignore": `.terraform/
*.tfstate
*.tfstate.backup
.terraform.lock.hcl
`,
	}

	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", name, err)
		}
	}
	return nil
}

// ─── YAML Generator (Ansible) ───

type YAMLGenerator struct{}

func (g *YAMLGenerator) FileExtension() string { return ".yml" }

func (g *YAMLGenerator) Generate(resources []parser.Resource) (string, error) {
	var b strings.Builder

	b.WriteString("# Generated by IaC Studio\n")
	b.WriteString("---\n")
	b.WriteString("- name: IaC Studio Playbook\n")
	b.WriteString("  hosts: all\n")
	b.WriteString("  become: true\n")
	b.WriteString("  tasks:\n")

	for _, res := range resources {
		name := res.Name
		if name == "" {
			name = res.Type
		}
		b.WriteString(fmt.Sprintf("    - name: %s\n", name))
		b.WriteString(fmt.Sprintf("      %s:\n", res.Type))
		for k, v := range res.Properties {
			switch val := v.(type) {
			case bool:
				if val {
					b.WriteString(fmt.Sprintf("        %s: yes\n", k))
				} else {
					b.WriteString(fmt.Sprintf("        %s: no\n", k))
				}
			default:
				b.WriteString(fmt.Sprintf("        %s: \"%v\"\n", k, val))
			}
		}
		b.WriteString("\n")
	}

	return b.String(), nil
}

func (g *YAMLGenerator) WriteScaffold(dir string) error {
	files := map[string]string{
		"site.yml": `# Ansible playbook managed by IaC Studio
---
- name: Main Playbook
  hosts: all
  become: true
  tasks: []
`,
		"inventory.ini": `[all]
# Add your hosts here
# web1 ansible_host=192.168.1.10
# db1  ansible_host=192.168.1.20

[all:vars]
ansible_user=deploy
ansible_python_interpreter=/usr/bin/python3
`,
		"ansible.cfg": `[defaults]
inventory = inventory.ini
host_key_checking = False
retry_files_enabled = False
`,
		".gitignore": `*.retry
.vault_pass
`,
	}

	// Create roles directory
	os.MkdirAll(filepath.Join(dir, "roles"), 0755)
	os.MkdirAll(filepath.Join(dir, "group_vars"), 0755)

	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", name, err)
		}
	}
	return nil
}
