package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/iac-studio/iac-studio/internal/catalog"
	"github.com/iac-studio/iac-studio/internal/parser"
)

// Generator produces IaC code from structured resources.
type Generator interface {
	Generate(resources []parser.Resource) (string, error)
	WriteScaffold(dir string) error
	FileExtension() string
}

// ForTool returns the appropriate generator.
func ForTool(tool string) Generator {
	switch tool {
	case "terraform", "opentofu":
		return &HCLGenerator{tool: tool}
	case "ansible":
		return &YAMLGenerator{}
	default:
		return &HCLGenerator{tool: "terraform"}
	}
}

// ─── HCL Generator (Terraform / OpenTofu) ───

type HCLGenerator struct {
	tool string
}

func (g *HCLGenerator) FileExtension() string { return ".tf" }

func (g *HCLGenerator) Generate(resources []parser.Resource) (string, error) {
	var b strings.Builder

	b.WriteString("# Generated by IaC Studio\n")
	b.WriteString("# Do not remove this comment — it enables bidirectional sync\n\n")

	// Detect which providers are needed and emit correct provider blocks
	hasAWS, hasGCP, hasAzure := false, false, false
	for _, res := range resources {
		switch {
		case strings.HasPrefix(res.Type, "aws_"):
			hasAWS = true
		case strings.HasPrefix(res.Type, "google_"):
			hasGCP = true
		case strings.HasPrefix(res.Type, "azurerm_"):
			hasAzure = true
		}
	}
	if hasAWS {
		b.WriteString("provider \"aws\" {\n  region = \"us-east-1\"\n}\n\n")
	}
	if hasGCP {
		b.WriteString("provider \"google\" {\n  project = \"my-project\"\n  region  = \"us-central1\"\n}\n\n")
	}
	if hasAzure {
		b.WriteString("provider \"azurerm\" {\n  features {}\n}\n\n")
	}

	// Build index: resource type -> list of (name, id) for reference generation.
	// Keyed by type so we can find the target by type AND by explicit property ref.
	typeInstances := make(map[string][]string) // e.g., "aws_vpc" -> ["main", "secondary"]
	for _, res := range resources {
		typeInstances[res.Type] = append(typeInstances[res.Type], res.Name)
	}

	// Build connection rules from catalog
	cat := catalog.GetCatalog(g.tool)
	connectsVia := make(map[string]map[string]string)
	for _, cr := range cat.Resources {
		if len(cr.ConnectsVia) > 0 {
			connectsVia[cr.Type] = cr.ConnectsVia
		}
	}

	for _, res := range resources {
		b.WriteString(fmt.Sprintf("resource \"%s\" \"%s\" {\n", res.Type, res.Name))

		// Emit connection references with provider-correct attribute syntax
		emittedFields := make(map[string]bool)
		if connections, ok := connectsVia[res.Type]; ok {
			for field, targetType := range connections {
				// Skip if user already set a literal value
				if _, hasLiteral := res.Properties[field]; hasLiteral {
					continue
				}
				// Find target — use explicitly connected instance if in properties,
				// otherwise fall back to first instance of the target type
				instances := typeInstances[targetType]
				if len(instances) == 0 {
					continue
				}
				// Use the first instance. When edges are sent via sync, the
				// correct target will be in Properties["__edge_<field>"].
				targetName := instances[0]
				if edgeTarget, ok := res.Properties["__edge_"+field]; ok {
					targetName = fmt.Sprintf("%v", edgeTarget)
					delete(res.Properties, "__edge_"+field)
				}

				ref := resolveReference(res.Type, field, targetType, targetName)
				b.WriteString(fmt.Sprintf("  %s = %s\n", field, ref))
				emittedFields[field] = true
			}
		}

		for k, v := range res.Properties {
			if emittedFields[k] || strings.HasPrefix(k, "__edge_") {
				continue
			}
			writeHCLValue(&b, k, v)
		}
		b.WriteString("}\n\n")
	}

	return b.String(), nil
}

// resolveReference returns the correct Terraform reference syntax for a
// connection field based on the provider. Different providers use different
// attribute shapes:
//   - AWS: most fields use .id (vpc_id = aws_vpc.main.id)
//   - GCP: uses .name, .self_link, or .id depending on the field
//   - Azure: uses .id for most, .name for name-based references
func resolveReference(sourceType, field, targetType, targetName string) string {
	ref := fmt.Sprintf("%s.%s", targetType, targetName)

	// GCP-specific reference patterns
	if strings.HasPrefix(targetType, "google_") {
		switch {
		case field == "network" || field == "subnetwork":
			return ref + ".self_link"
		case field == "router" || field == "instance" || field == "cluster":
			return ref + ".name"
		case field == "managed_zone":
			return ref + ".name"
		case field == "key_ring":
			return ref + ".id"
		case strings.HasSuffix(field, "_id"):
			return ref + ".id"
		default:
			return ref + ".name"
		}
	}

	// Azure-specific reference patterns
	if strings.HasPrefix(targetType, "azurerm_") {
		switch {
		case strings.HasSuffix(field, "_id") || strings.HasSuffix(field, "_plan_id"):
			return ref + ".id"
		case field == "resource_group_name":
			return ref + ".name"
		case field == "virtual_network_name" || field == "storage_account_name":
			return ref + ".name"
		case strings.HasSuffix(field, "_name"):
			return ref + ".name"
		default:
			return ref + ".id"
		}
	}

	// AWS — almost everything uses .id
	return ref + ".id"
}

// writeHCLValue writes a single key = value line with proper type handling.
func writeHCLValue(b *strings.Builder, k string, v interface{}) {
	switch val := v.(type) {
	case bool:
		b.WriteString(fmt.Sprintf("  %s = %t\n", k, val))
	case float64:
		if val == float64(int64(val)) {
			b.WriteString(fmt.Sprintf("  %s = %d\n", k, int64(val)))
		} else {
			b.WriteString(fmt.Sprintf("  %s = %g\n", k, val))
		}
	case int:
		b.WriteString(fmt.Sprintf("  %s = %d\n", k, val))
	case int64:
		b.WriteString(fmt.Sprintf("  %s = %d\n", k, val))
	case []interface{}:
		b.WriteString(fmt.Sprintf("  %s = [", k))
		for i, item := range val {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", fmt.Sprintf("%v", item)))
		}
		b.WriteString("]\n")
	case map[string]interface{}:
		b.WriteString(fmt.Sprintf("  %s = {\n", k))
		for mk, mv := range val {
			b.WriteString(fmt.Sprintf("    %s = %q\n", mk, fmt.Sprintf("%v", mv)))
		}
		b.WriteString("  }\n")
	default:
		b.WriteString(fmt.Sprintf("  %s = %q\n", k, fmt.Sprintf("%v", val)))
	}
}

func (g *HCLGenerator) WriteScaffold(dir string) error {
	files := map[string]string{
		"main.tf": fmt.Sprintf(`# %s project managed by IaC Studio

provider "aws" {
  region = var.region
}
`, g.tool),
		"variables.tf": `variable "region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "dev"
}
`,
		"outputs.tf": `# Outputs will be generated as resources are added
`,
		".gitignore": `.terraform/
*.tfstate
*.tfstate.backup
.terraform.lock.hcl
`,
	}

	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", name, err)
		}
	}
	return nil
}

// ─── YAML Generator (Ansible) ───

type YAMLGenerator struct{}

func (g *YAMLGenerator) FileExtension() string { return ".yml" }

func (g *YAMLGenerator) Generate(resources []parser.Resource) (string, error) {
	var b strings.Builder

	b.WriteString("# Generated by IaC Studio\n")
	b.WriteString("---\n")
	b.WriteString("- name: IaC Studio Playbook\n")
	b.WriteString("  hosts: all\n")
	b.WriteString("  become: true\n")
	b.WriteString("  tasks:\n")

	for _, res := range resources {
		name := res.Name
		if name == "" {
			name = res.Type
		}
		b.WriteString(fmt.Sprintf("    - name: %s\n", name))
		b.WriteString(fmt.Sprintf("      %s:\n", res.Type))
		for k, v := range res.Properties {
			switch val := v.(type) {
			case bool:
				if val {
					b.WriteString(fmt.Sprintf("        %s: yes\n", k))
				} else {
					b.WriteString(fmt.Sprintf("        %s: no\n", k))
				}
			default:
				b.WriteString(fmt.Sprintf("        %s: \"%v\"\n", k, val))
			}
		}
		b.WriteString("\n")
	}

	return b.String(), nil
}

func (g *YAMLGenerator) WriteScaffold(dir string) error {
	files := map[string]string{
		"site.yml": `# Ansible playbook managed by IaC Studio
---
- name: Main Playbook
  hosts: all
  become: true
  tasks: []
`,
		"inventory.ini": `[all]
# Add your hosts here
# web1 ansible_host=192.168.1.10
# db1  ansible_host=192.168.1.20

[all:vars]
ansible_user=deploy
ansible_python_interpreter=/usr/bin/python3
`,
		"ansible.cfg": `[defaults]
inventory = inventory.ini
host_key_checking = False
retry_files_enabled = False
`,
		".gitignore": `*.retry
.vault_pass
`,
	}

	// Create roles directory — best-effort; WriteFile below will surface any
	// real failures when it tries to create individual files inside.
	_ = os.MkdirAll(filepath.Join(dir, "roles"), 0755)
	_ = os.MkdirAll(filepath.Join(dir, "group_vars"), 0755)

	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", name, err)
		}
	}
	return nil
}
